### ISSUE TITLE
run.sh no executa en ubuntu 20.04

### ISSUE THREAD

**Issue by RamiroMF** [gdmatrix/gdmatrix#8]
Estic intentant executar el programa de signatura seguint els instruccions del web (executar el ./run.sh) i no funciona. Llença elñ segúent error:
./run.sh
Failed to execute process './run.sh'. Reason:
exec: Exec format error
The file './run.sh' is marked as an executable but could not be run by the operating system.

Però si executo el command que hi ha a dins de l'script si que executa el programa. Tot i això a l'intentar firmar em diu que no hi ha cap certificat seleccionat.

**Comment by realor** [comment]
Amb ubuntu 20.04 jo no he tingut problemes per executar el script run.sh que hi ha en el zip que et pots baixar del web de l'Ajuntament: [https://www.santfeliu.cat/apps/client.faces](https://www.santfeliu.cat/apps/client.faces)

Amb Linux aquesta aplicació només permet signar amb un certificat pkcs12. Per afegir-lo, fes botó dret del ratolí i escull l'opció "Afegir certificat PKCS12". Selecciona el fitxer p12 o pfx i introdueix la paraula de pas. Un cop afegit ja podràs signar el document.

**Comment by RamiroMF** [comment]
L'error passa fent servir fish shell on et retorna el següent error:
./run.sh
Failed to execute process './run.sh'. Reason:
exec: Exec format error
The file './run.sh' is marked as an executable but could not be run by the operating system.

Si executes l'script fent servir la terminal bash sense res més si que funciona. Pots tancar l'issue si vols. Merci

**Comment by RamiroMF** [comment]
De fet afegint #!/bin/bash a la primera linia funciona amb fish també. Et faig un PR amb els canvis.
